package java.Laborator1.Compulsory;

/**
 * This is the main method, here we use what we built
 */
public class Main {
    public static void main(String[] args) {
        /**
         * Here is called the printHelloWorld method from Utils class
         * It is a static method, we can use it with no problems
         */
        Utils.printHelloWorld();
        /**
         * This one is a little tricky
         * This line of code prints the language stored on the position generated by the generateRandomIndex method from Utils class
         */
        System.out.println(Constants.languages[Utils.generateRandomIndex()]);
    }
}